const CACS_BY_TOWN = {
  hartford: "23",
  berlin: "19",
  bristol: "19",
  burlington: "19",
  "new britain": "19",
  plainville: "19",
  plymouth: "19",
  southington: "19",
  avon: "18",
  canton: "18",
  farmington: "18",
  simsbury: "18",
  "west hartford": "18",
  bloomfield: "17",
  "east granby": "17",
  "east windsor": "17",
  enfield: "17",
  granby: "17",
  somers: "17",
  stafford: "17",
  suffield: "17",
  windsor: "17",
  "windsor locks": "17",
  "east hartford": "16",
  glastonbury: "16",
  marlborough: "16",
  newington: "16",
  "rocky hill": "16",
  wethersfield: "16",
  andover: "15",
  bolton: "15",
  ellington: "15",
  hebron: "15",
  manchester: "15",
  "south windsor": "15",
  tolland: "15",
  vernon: "15"
};

module.exports = { CACS_BY_TOWN };

